export{  default as Home} from './Home/Home'
export{  default as News} from './News/News'
export{  default as Coins} from './Coins/Coins'
export{  default as About} from './About/About'
export{  default as More} from './More/More'
export{  default as Exchanges} from './Exchanges/Exchanges'